version: '3.8'

services:
  comic-front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./comic-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
